"""Parser conformance: what a line means, checked against bash.

The `CORPUS` table was generated by running each line through
`bash -c` with `echo`/`printf` replaced by a function that prints its
argv NUL-separated, and comparing with `Parser`. Regenerate it the same
way when adding rows; the one place Zem deliberately differs (no
word-splitting of `$VAR`) has its own test below.
"""

import os

import pytest

from zem.config.settings import AppConfig
from zem.core.parser import Parser
from zem.core.scan import needs_continuation, split_words
from zem.errors.parser_error import ParseError

CFG = AppConfig()
OPS = CFG.operators
VARS = {"X": "hello", "E": "", "Q": "it's", "SP": "a b"}


def _units(line, variables=None, aliases=None, substitutor=None):
    return Parser(line, variables or {}, aliases or {}, CFG, substitutor).parse()


def _argv(line, variables=None, aliases=None):
    cmd = _units(line, variables, aliases)[0]["pipeline"][0]
    return [cmd["name"], *cmd["args"]]


def _names(units):
    return [[c["name"] for c in u["pipeline"]] for u in units]


# -- corpus, bash-verified ---------------------------------------------------

CORPUS = [
    # backslash inside double quotes escapes only $ " \ ` and newline
    (r'echo "a\nb"', ["echo", "a\\nb"]),
    (r'printf "%s\n" one two', ["printf", "%s\\n", "one", "two"]),
    (r'echo "path\to" "c:\\d"', ["echo", "path\\to", "c:\\d"]),
    (r'echo "e\$f" "g\"h" "i\`j"', ["echo", "e$f", 'g"h', "i`j"]),
    (r'echo "$X\n$X"', ["echo", "hello\\nhello"]),
    # single quotes and unquoted escapes are unchanged
    (r"echo 'a\nb' 'it'\''s'", ["echo", "a\\nb", "it's"]),
    (r"echo a\ b a\\b \$X", ["echo", "a b", "a\\b", "$X"]),
    (r'echo "$Q"', ["echo", "it's"]),
    # comments start at a word boundary and run to the end of the line
    (r"echo hi # comment", ["echo", "hi"]),
    (r"echo hi # a | b ; c && d", ["echo", "hi"]),
    (r'echo a#b "#c" \#d', ["echo", "a#b", "#c", "#d"]),
    (r"echo a;#b", ["echo", "a"]),
    # variables
    (r'echo ${X}y "${X}"', ["echo", "helloy", "hello"]),
    (r"echo $E-$X", ["echo", "-hello"]),
    (r'echo a$E.b "$E" $E', ["echo", "a.b", ""]),
    (r"echo $#", ["echo", "0"]),
    # words and empty arguments
    (r'echo "" x ""', ["echo", "", "x", ""]),
    (r"echo    a   b", ["echo", "a", "b"]),
    (r'echo a"b"c', ["echo", "abc"]),
    (r'echo "a  b"', ["echo", "a  b"]),
]


@pytest.mark.parametrize("line, expected", CORPUS, ids=[c[0] for c in CORPUS])
def test_argv_matches_bash(line, expected):
    assert _argv(line, VARS) == expected


def test_deliberate_difference_variables_are_not_word_split():
    # fish semantics, on purpose: `$SP` stays one word (bash gives two).
    assert _argv("echo $SP", VARS) == ["echo", "a b"]


# -- double quotes -------------------------------------------------------------

def test_backslash_newline_inside_double_quotes_continues_the_line():
    assert needs_continuation('echo "abc\\', OPS)
    assert _argv('echo "abc\\\ndef"') == ["echo", "abc\ndef"]


def test_split_words_keeps_a_literal_backslash_in_double_quotes():
    assert [w.value for w in split_words(r'printf "%s\n" "a\"b"', OPS)] == [
        "printf", "%s\\n", 'a"b',
    ]


def test_variable_value_with_quotes_inside_double_quotes():
    assert _argv('echo "$Q"', VARS) == ["echo", "it's"]
    assert _argv('echo "$V"', {"V": 'a"b\\c$d'}) == ["echo", 'a"b\\c$d']


# -- comments --------------------------------------------------------------------

def test_comment_hides_operators_from_the_splitter():
    units = _units("echo a # b | c ; d && e")
    assert _names(units) == [["echo"]]


def test_comment_is_not_a_continuation():
    assert not needs_continuation("echo a # trailing |", OPS)
    assert not needs_continuation("echo a # trailing \\", OPS)


def test_comment_inside_quotes_is_text():
    assert _argv('echo "a # b" \'# c\'') == ["echo", "a # b", "# c"]


def test_split_words_drops_the_comment():
    assert [w.value for w in split_words("git add # files", OPS)] == ["git", "add"]


# -- background `&` ------------------------------------------------------------

def test_single_ampersand_separates_units():
    units = _units("sleep 1 & echo after")
    assert _names(units) == [["sleep"], ["echo"]]
    assert units[0]["pipeline"][0]["args"] == ["1"]
    assert units[0]["pipeline"][0]["background"] is True
    assert units[0]["logic"] == ";"
    assert units[1]["pipeline"][0]["background"] is False


def test_trailing_ampersand_marks_last_stage_only():
    units = _units("a | b &")
    assert [c["background"] for c in units[0]["pipeline"]] == [False, True]
    assert len(units) == 1


def test_ampersand_in_redirections_is_not_a_separator():
    (unit,) = _units("cmd &> both")
    assert unit["pipeline"][0]["stdout_file"] == "both"
    (unit,) = _units("cmd >&2 2>&1")
    assert unit["pipeline"][0]["stdout_to_stderr"] is False  # last one wins
    assert unit["pipeline"][0]["stderr_to_stdout"] is True
    (unit,) = _units("cmd >&2 &")
    assert unit["pipeline"][0]["background"] is True


def test_ampersand_then_and_is_an_empty_command():
    with pytest.raises(ParseError):
        _units("a & && b")


# -- aliases are re-parsed as text -------------------------------------------

def test_alias_body_with_a_pipe():
    units = _units("x", aliases={"x": "echo a | tr a b"})
    assert _names(units) == [["echo", "tr"]]


def test_alias_body_with_logic_keeps_the_callers_operator():
    units = _units("y && echo done", aliases={"y": "git pull && uv sync"})
    assert _names(units) == [["git"], ["uv"], ["echo"]]
    assert [u["logic"] for u in units] == ["&&", "&&", None]


def test_alias_body_with_semicolon_and_background_tail():
    units = _units("two &", aliases={"two": "echo 1; echo 2"})
    assert _names(units) == [["echo"], ["echo"]]
    assert [c["background"] for u in units for c in u["pipeline"]] == [False, True]


def test_alias_in_a_later_pipeline_stage():
    units = _units("echo abc | up | cat", aliases={"up": "tr a-z A-Z"})
    assert _names(units) == [["echo", "tr", "cat"]]


def test_alias_body_with_redirect_and_comment():
    (unit,) = _units("e", aliases={"e": "echo out > f # note"})
    assert unit["pipeline"][0]["stdout_file"] == "f"
    assert unit["pipeline"][0]["args"] == ["out"]


def test_quoted_or_escaped_first_word_bypasses_aliases():
    aliases = {"ls": "ls -F"}
    assert _argv("'ls' /", aliases=aliases) == ["ls", "/"]
    assert _argv("\\ls /", aliases=aliases) == ["ls", "/"]
    assert _argv("ls /", aliases=aliases) == ["ls", "-F", "/"]


def test_parameterised_alias_keeps_the_arguments_quoting():
    aliases = {"gc": "git commit -m $1"}
    assert _argv('gc "my msg" extra', aliases=aliases) == [
        "git", "commit", "-m", "my msg", "extra",
    ]


def test_parameterised_alias_ten_is_not_one_zero():
    aliases = {"p": "echo $10 $1"}
    assert _argv("p 1 2 3 4 5 6 7 8 9 ten", aliases=aliases) == ["echo", "ten", "1"]


def test_empty_alias_expands_to_nothing():
    with pytest.raises(ParseError):
        _units("nothing", aliases={"nothing": ""})
    assert _argv("nothing echo hi", aliases={"nothing": ""}) == ["echo", "hi"]


def test_alias_recursion_stops_at_itself_and_at_cycles():
    assert _argv("ls -a", aliases={"ls": "ls -F"}) == ["ls", "-F", "-a"]
    assert _argv("a x", aliases={"a": "b", "b": "a"}) == ["a", "x"]


# -- special parameters and empty expansions --------------------------------

def test_special_parameters():
    assert _argv("echo $$") == ["echo", str(os.getpid())]
    assert _argv("echo $0 $# $@x $*y") == ["echo", "zem", "0", "x", "y"]
    assert _argv("echo $!", {"!": "4242"}) == ["echo", "4242"]
    assert _argv("echo $1x", {"1": "one"}) == ["echo", "onex"]


def test_unset_variable_vanishes_when_unquoted():
    assert _argv("ls $UNSET") == ["ls"]
    assert _argv("ls $UNSET$ALSO") == ["ls"]
    assert _argv("ls $UNSET a") == ["ls", "a"]


def test_unset_variable_in_quotes_is_an_empty_argument():
    assert _argv('ls "$UNSET"') == ["ls", ""]
    assert _argv("ls ''$UNSET") == ["ls", ""]


def test_empty_substitution_vanishes_when_unquoted():
    units = _units("echo $(x) y", substitutor=lambda s: "\n")
    assert units[0]["pipeline"][0]["args"] == ["y"]
